### ISSUE TITLE
Move topics from main.tex

### ISSUE THREAD

**Issue by GusSand** [Atcold/SP19-DL-collaborative-notes#89]
- Some people haven't moved their stuff in the main.tex file. Their initials and names are below.  Can you please move ? 
	- EN - Erfan Noury
	- PK - Parvez Kose
	- BA - Ben Ahlbrand
	- KF - Karla Fejfarova

**Comment by Atcold** [comment]
Closing, since we're starting afresh.
Thank you for this issue.
