### ISSUE TITLE
Should we merge : Chapter 16 and Chapter 17.8 and 17.9 ?

### ISSUE THREAD

**Issue by ishacusp** [Atcold/SP19-DL-collaborative-notes#91]
What do people think about merging Chapter 16 - optimization (architectures part) and Chapter 17 - back-propagation in practice (practical part)? I personally don’t think we should merge those two. But what do people in general think about it ?

**Comment by Atcold** [comment]
If they are not too short and not too repetitive, then we can keep them separate.
Who's suggesting the merge and why?

**Comment by tensor-flo** [comment]
I suggested the merge. At first, I thought 16.1 and 17.8 have the same content, but then I took a further look and realized only Fig 17.9 is duplicated, and it is not even being referred anywhere in chap 17. So I think we can just remove fig 17.9 and keep the two sections separated. Sorry for the confusion.
