### ISSUE TITLE
Sync github and Overleaf?

### ISSUE THREAD

**Issue by karlafej** [Atcold/SP19-DL-collaborative-notes#96]
There are 3 commits not synced to Overleaf + there are quite a few changes made by me and Ben not reflected here.

**Comment by bmahlbrand** [comment]
Hrmm, good point, at some point we did have track changes enabled in overleaf, but its possible that it's gotten disabled?

**Comment by michaelgold** [comment]
There was a merge conflict. I believe I fixed it last night. Please confirm

**Comment by bmahlbrand** [comment]
I checked afterwards and it should've been.
